package com.azavea;

import com.azavea.Node;

import java.util.Arrays;


/**
 * The bus class. This class represents a school bus and acts as the
 * anchor type for chains of sources and sinks (as generated by
 * OptaPlanner).
 *
 * @author James McClain
 */
public class Bus implements SourceOrSinkOrAnchor {

    private Node node;
    private SourceOrSink next;
    private int n;

    public Bus() { }

    /**
     * Construct a bus from a node (location) and number.
     *
     * @author James McClain
     * @param  node A {@link Node} representing the home garage of the bus
     * @param  n    The number of this bus.  The node (garage) and number of a bus uniquely identifies it.
     */
    public Bus(Node node, int n) {
        this.node = node;
        this.n = n;
    }

    @Override public SourceOrSink getNext() { return this.next; }
    @Override public void setNext(SourceOrSink next) { this.next = next; }

    @Override public Node getNode() { return this.node; };
    @Override public void setNode(Node node) { this.node = node; }

    @Override public Bus getBus() { return this; }
    @Override public void setBus(Bus bus) { /* Ø */ }

    @Override
    public int hashCode() {
        return this.getNode().toString().hashCode();
    }

    public boolean equals(Object other) {
        if (other instanceof String)
            return this.getNode().getUuid() == ((String)other);
        else if (!(other instanceof Bus))
            return false;
        else
            return this.getNode().getUuid() == ((Bus)other).getNode().getUuid();
    }

    public String toString() { return "ANCHOR[" + this.node.toString() + "(" + this.n + ")]"; }

    /**
     * The amount of time that it takes to travel between the home
     * garage of this bus and the given {@link SourceOrSinkOrAnchor}.
     *
     * @author James McClain
     * @param  other The other location from which to compute the drive time
     * @return The amount of time in seconds
     */
    public int time(SourceOrSinkOrAnchor other) {
        return this.getNode().time(other.getNode());
    }

    /**
     * The amount of time that it takes to travel between teh home
     * garage of this bus and the given {@link Node}.
     *
     * @author James McClain
     * @param  other The other location from which to compute the drive time
     * @return The amount of time in seconds
     */
    public int time(Node other) {
        return this.getNode().time(other);
    }

    /**
     * The distance between the the home garage of this bus and the
     * given {@link SourceOrSinkOrAnchor}.
     *
     * @author James McClain
     * @param  other The other location from which to compute the distance
     * @return The distance in feet
     */
    public double distance(SourceOrSinkOrAnchor other) {
        return this.getNode().distance(other.getNode());
    }

    /**
     * The distance between the the home garage of this bus and the
     * given {@link Node}.
     *
     * @author James McClain
     * @param  other The other location from which to compute the distance
     * @return The distance in feet
     */
    public double distance(Node other) {
        return this.getNode().distance(other);
    }
}
