package com.example;
    dialect "java"

import org.optaplanner.core.api.score.buildin.hardsoftlong.HardSoftLongScoreHolder;

import com.example.Bus;
import com.example.School;
import com.example.SourceOrSink;
import com.example.SourceOrSinkOrAnchor;
import com.example.Stop;
import com.example.Student;

global HardSoftLongScoreHolder scoreHolder;

// Hard Constraints

rule "kids"
     when
         $s : Student()
     then
         Stop stop = $s.getStop();
         if (stop == null || !stop.getNode().equals($s.getNode())) { // XXX
             scoreHolder.addHardConstraintMatch(kcontext, - 2);
         }
         else {
             scoreHolder.addHardConstraintMatch(kcontext, - 1);
         }
end

rule "schoolFound"
     when
         $school : School(bus != null)
     then
         scoreHolder.addHardConstraintMatch(kcontext, + $school.getSinkSize());
end

// Soft Constraints

rule "busLeavetime"
     when
         $b : Bus(next != null)
     then
         if (!($b.equals("dummy")))
              scoreHolder.addSoftConstraintMatch(kcontext, -$b.time($b.getNext()));
end

rule "time"
     when
        $s : SourceOrSink(next != null, $b : bus)
     then
         if (!($b.equals("dummy")))
              scoreHolder.addSoftConstraintMatch(kcontext, - $s.time($s.getNext()));
end

rule "busReturnTime"
     when
         $s : SourceOrSink(next == null, $b : bus != null)
     then
         if (!($b.equals("dummy")))
              scoreHolder.addSoftConstraintMatch(kcontext, - $s.time($s.getBus()));
end
